@startuml
package com.pluralsight{

package com.pluralsight.product{

abstract class MenuItem #lightblue{
-name: String

+MenuItem(name: String)
+getName(): String
+{abstract} displayDetails(): void

}

class Sandwich #DEB887 extends MenuItem{
-size: String
-breadType: String
-toppings: List<Topping>
-isToasted: boolean

+Sandwich(name: String, size: String, breadType: String, isToasted: boolean)
+customize(): void
+addTopping(Topping topping): void
+calculatePrice(): double
+displayDetails(): void
}

abstract class Topping #F0E68C extends MenuItem {
-toppingType: String
+Topping(name: String, toppingType: String)
+{abstract} displayDetails(): void
}

class Drink #00FFFF extends MenuItem {
-size: String
-price: double

+Drink(name: String, size: String)
+getSize(): String
+getPrice(): double
+displayDetails(): void
}

class Chip #FFDAB9 extends MenuItem {
-price: double

+Chip(name: String)
+getPrice(): double
+displayDetails(): void
}


class PremiumTopping #FF7F50 extends Topping {
-isExtra: boolean
+PremiumTopping(name: String, toppingType: String)
+isExtra(): boolean
+displayDetails(): void
}

class RegularTopping #FF7F50 extends Topping {
-isExtra: boolean
+RegularTopping(name: String, toppingType: String, isExtra: boolean)
+displayDetails(): void
}

class Sauces #91A3B0 extends RegularTopping{

+Sauces(name: String, toppingType: String, isExtra: boolean)

}

class Sides #91A3B0 extends RegularTopping{

+Sides(name: String, toppingType: String, isExtra: boolean)
}


}

package com.pluralsight.service{

class Order #FFB6C1 {
-orderID: int
-customer: Customer
-sandwiches: List<Sandwich>
-drinks: List<Drink>
-chips: List<Chip>

+Order(orderID: int, customer: Customer)
+addSandwich(Sandwich sandwich): void
+addDrink(Drink drink): void
+addChip(Chip chip): void
+calculateTotal(): double
+generateReceipt(): void
}

class Customer #FFD700{
-name: String
-contactInfo: String

+Customer(name: String, contactInfo: String)
+getName(): String
+getContactInfo(): String
}

abstract class Report {
+abstract void generate()
}


class Receipt {
Order order

+Receipt(Order order)
+void generateFile()
}

class SalesReport extends Report {
+void generate()
}

class Menu {
List<Sandwich> sandwiches
List<Drink> drinks
List<Chip> chips
List<Topping> toppings

+ Menu()
+void updatePrices()
+List<Sandwich> getSandwiches()
+List<Drink> getDrinks()
+List<Chip> getChips()
List<Topping> getToppings()
}

class DatabaseManager {
+saveOrder(Order order): void
+Menu loadMenu()
+Order retrieveOrder(int orderID)
}


}

}


@enduml
